### ISSUE TITLE
CRUD para tabela de User, Seed e Factory

### ISSUE THREAD

**Issue by ricardfo** [fflch/minibib#5]
Modificar a migration de Users já existente, adicionando os seguinte campo:

>  **status** do tipo **string**, que receberá a informação 'Ativo' ou 'Inativo'.

O campo de **passoword** deverá receber nullable pois utilizaremos a senha única para autenticar o usuário.

O campo **ID** desta tabela receberá o número USP dos usuários que poderão administrar o sistema.

Após isso criar o controller com os métodos do CRUD, as rotas, views e fazer os seeds e factory.

**Comment by thiagogomesverissimo** [comment]
Essa issuefoi feita @powdn ?
