### ISSUE TITLE
Criar CRUD para Empréstimo

### ISSUE THREAD

**Issue by ricardfo** [fflch/minibib#6]
Criar a migration para Empréstimo com os seguintes campos:

> **id_instance** precisa ser do mesmo tipo do campo id da tabela Instance, pois será uma chave estrangeira e receberá o id da instance que será emprestado;
> **data_emprestimo** do tipo data;
> **data_devolucao** do tipo data;
> **id_user** precisa ser do mesmo tipo do campo id da tabela Users, pois será uma chave estrangeira e receberá o id do usuário (Administrador do Sistema) que efetuou o empréstimo;
> **codpes** do tipo string, será o número USP de quem está emprestando.

Após isso criar o Model, Controller, Views, Seeder, Factory e as Rotas.

**Comment by thiagogomesverissimo** [comment]
@ricardfo eu esqueci de comentar algo. Na tabela Record terá o cadastro do material (livro, revista, etc). Porém, pode-se ter vários exemplares do mesmo Record. Assim, o que será emprestado de fato será o exemplar. Esse exemplar além de ter um record_id apontando para o material, terá campo próprio chamado tombo, que é a identificação do exemplar. O empréstimo então é baseado nessa tabela de exemplares e não na tabela Record.

**Comment by thiagogomesverissimo** [comment]
Como chamamos o cadastro de Record, a tabela de exemplares poderia ser *Instance*

**Comment by ricardfo** [comment]
@thiago a tabela Instance não terá só livro para empréstimo, então os outros tipos de materiais teram tombo também? 
Outra coisa, um tombo diferente é atribuido para cada exemplar ou usa-se o mesmo para todos os exemplares, porque senão precisaremos de um campo de quantidade na tabela e controlar como um sistema de estoque o empréstimo.

**Comment by thiagogomesverissimo** [comment]
Instance terá apenas dois campos: record_id e tombo. Quem tem o tombo é o exemplar e não o livro (Record). E cada exemplar tem seu tombo, mesmo que sejam o mesmo livro.
